---
title: "Statistiques descriptives"
author: "Mame Balla BOUSSO, élève en ISEP2_2024"
date: "2024-03-08"
output:
  pdf_document: default
  word_document: default
---

_**DES STATISTIQUES DESCRIPTIVES**_:

**LA TAILLE**

```{r setup, include=FALSE}
Nom<- c("BOUSSO","COULIBALY","DIAKHATE","DIAW","DIENG","FAYE","HILDEGARDE","SARAH-LAURE","NIANG","NIASS","KANE","NDONG","NGEMFUOU","DE LE FLECHE","Rayan", "SENE")
Prénom<-c("Mame Balla","Khadidiatou", "Khadidiatou","Awa","Samba","Ameth","Edima Biyenda","Fougwoug","Papa Ahmadou","Ahmadou","Alioune Abdou Salam","Tamsir","Célia","Jeanne","Ange","Malick")
Age<-c("23 ans","19 ans","19 ans","20 ans","19 ans","21 ans","20 ans","20 ans","19 ans","20 ans","19 ans","20 ans","20 ans","21 ans", "18 ans","19 ans")
Mention_ISEP<-c("Bien","Excellent","Tbien","Tbien","TBien","Tbien","Tbien","Tbien","Tbien","Tbien","Tbien","Tbien","Tbien","Tbien","Tbien","Tbien")
Taille<-c(185,163,195,180,175,180,175,160,185,163,195,180,175,180,175,184)
Poids<-c(62,58,59,58,59,75,62,57,65,58,59,80,58,75,57,63)

nombre_variables <- 15
nombre_observations <- 304

# Créer un data.frame 
ma_base_de_donnees <- data.frame(
  Nom<- rep(Nom,19),
  Prénom<- rep(Prénom,19),
  Age<- rep(Age,19),
  Mention<- rep(Mention_ISEP,19),
  Taille<- rep(Taille,19),
  Poids<- rep(Poids,19),
  Célibataire<- sample(c("Oui", "Non"), nombre_observations, replace = TRUE),  # Variable catégorielle
  Sexe<- sample(c("Masculin", "Féminim"), nombre_observations, replace = TRUE),  # Variable catégorielle
  Matricule1<- rpois(nombre_observations, lambda = 3),  # Variable numérique avec distribution de Poisson
  Chiffre_choisi<- factor(sample(letters[1:5], nombre_observations, replace = TRUE)),  # Variable factorielle
  Fiancé<- sample(c("Oui", "Non"), nombre_observations, replace = TRUE),  # Variable binaire
  Lettre_préféré<- sample(letters[10:15], nombre_observations, replace = TRUE),  # Variable catégorielle
  Matricule2<- rnorm(nombre_observations),
  Niveau_R<- sample(c("Très Bon", "Bon","Assez Bon","Médiocre"), nombre_observations, replace = TRUE),
  Logicel_préféré<- sample(c("Python", "Stata","SPSS","R","Excel"), nombre_observations, replace = TRUE))

```

```{r,echo=FALSE}
summary(Taille)
```
**LE POIDS**
```{r,echo=FALSE}
summary(Poids)
```

**GRAPHIQUES**

```{r echo=FALSE}
poids_cat <- cut(Poids, breaks = c(55, 60, 70, 80), labels = c("Faible", "Moyen", "Fort"))
library(ggplot2)
ggplot(ma_base_de_donnees, aes(x=Age, y=Fiancé)) +
  geom_bar(color="pink",stat="identity", position="dodge") +
  labs(title="HISTOGRAMME DE LA SITUATION DE MATRIMONIALE PAR AGE",
       x="AGE",
       y="TAILLE") +
  theme_minimal() +
  geom_point()
```


```{r echo=FALSE}
taille_cat <- cut(Taille, breaks = c(150, 170, 180, 200), labels = c("Petite", "Moyenne", "Grande"))
library(ggplot2)
ggplot(color="pink",ma_base_de_donnees, aes(x=Age, y=taille_cat)) +
  geom_bar(stat="identity", position="dodge") +
  labs(title="HISTOGRAMME DE LA TAILLE PAR AGE",
       x="AGE",
       y="TAILLE") +
  theme_minimal() +
  geom_point()
```









